import type { Metadata } from "next";
import "./globals.css";
import Providers from "./context/providers";
import { SessionProvider } from "./context/sessionProvider";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Store",
    default: "Next Store", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SessionProvider>{children}</SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
